### ISSUE TITLE
Backup using script results in error with Traceback

### ISSUE THREAD

**Issue by jberanek** [obergt/Isilon_Tools#1]
Cloned the repository and attempted a backup operation, results below:

```
./isi_tools.py -t exports -u johnb -pw "MYPASSWORD" -n smartconnect.isilon.example.com backup
Traceback (most recent call last):
  File "./isi_tools.py", line 110, in <module>
    main()
  File "./isi_tools.py", line 104, in main
    api = isilon.API(args.clustername, args.user, args.password)
  File "/home/AD/johnb/Isilon_Tools/isilon/__init__.py", line 29, in __init__
    self.session = session.Session(clustername, username, password, services)
  File "/home/AD/johnb/Isilon_Tools/isilon/session.py", line 35, in __init__
    self.log.addHandler(logging.NullHandler())
AttributeError: 'module' object has no attribute 'NullHandler'
```

**Comment by obergt** [comment]
which version of python do you have installed? which version of OneFS do
you have installed?
the script was checked on OneFS 7.1.
Also, Try to run the script from an external client that has access to the
isilon.

Thanks,
Tamir Obergot

**Comment by jberanek** [comment]
Python 2.6.6, attempted to backup config from a 7.1.1 cluster.

Script was run on an external client, not the Isilon cluster itself.

**Comment by jberanek** [comment]
Just tested with the non-standard Python 2.7.5 that my CentOS 6 client also has installed, and the script does not error out and appears to provide a valid backup file.

**Comment by obergt** [comment]
Great! I'm closing the issue but, I will still look into it and update with the conclusion.
